In [1]:
import random,math,copy,time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import (RandomForestClassifier,GradientBoostingClassifier)
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
import matplotlib.pyplot as plt
import math
from sklearn.utils import shuffle
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

from sklearn.model_selection import KFold
from sklearn.model_selection  import cross_val_score

In [2]:
df=pd.read_csv("/content/drive/MyDrive/target output/german dataset/csv_result-credit-g.csv")

df=shuffle(df)


features=[]

In [3]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
credit = df.apply(le.fit_transform)

In [4]:
df.head()


id checking_status  duration                  credit_history  \
135  136     no checking        12  critical/other existing credit   
936  937           >=200         9                   existing paid   
57    58     no checking        36  critical/other existing credit   
620  621        0<=X<200        21  critical/other existing credit   
312  313           >=200        24                   existing paid   

                 purpose  credit_amount    savings_status employment  \
135             radio/tv           1240  no known savings        >=7   
936             radio/tv            745              <100     1<=X<4   
57              radio/tv           9566              <100     1<=X<4   
620             business           3652              <100     4<=X<7   
312  furniture/equipment           3749              <100         <1   

     installment_commitment     personal_status  ... property_magnitude  age  \
135                       4  female div/dep/mar  ...        real estate   38   
936                       3  female div/dep/mar  ...        real estate   28   
57                        2  female div/dep/mar  ...                car   31   
620                       2         male single  ...     life insurance   27   
312                       2  female div/dep/mar  ...                car   26   

    other_payment_plans  housing existing_credits                 job  \
135                none      own                2             skilled   
936                none      own                1  unskilled resident   
57               stores      own                2             skilled   
620                none      own                2             skilled   
312                none      own                1             skilled   

     num_dependents own_telephone  foreign_worker class  
135               1           yes             yes  good  
936               1          none             yes   bad  
57                1          none             yes  good  
620               1          none             yes  good  
312               1          none             yes  good  

[5 rows x 22 columns]

In [5]:
credit.head()

id  checking_status  duration  credit_history  purpose  credit_amount  \
135  135                3         8               1        6            170   
936  936                2         5               3        6             54   
57    57                3        23               1        6            876   
620  620                0        15               1        0            644   
312  312                2        17               3        3            649   

     savings_status  employment  installment_commitment  personal_status  ...  \
135               4           3                       3                0  ...   
936               2           0                       2                0  ...   
57                2           0                       1                0  ...   
620               2           1                       1                3  ...   
312               2           2                       1                0  ...   

     property_magnitude  age  other_payment_plans  housing  existing_credits  \
135                   3   19                    1        1                 1   
936                   3    9                    1        1                 0   
57                    0   12                    2        1                 1   
620                   1    8                    1        1                 1   
312                   0    7                    1        1                 0   

     job  num_dependents  own_telephone  foreign_worker  class  
135    1               0              1               1      1  
936    3               0              0               1      0  
57     1               0              0               1      1  
620    1               0              0               1      1  
312    1               0              0               1      1  

[5 rows x 22 columns]

In [6]:
for k in range(22):
	features.append(str(k))


d=len(features)   # Flock (population) size
lt=len(features)
y=credit['class']
x=credit[credit.columns[0:21]]

In [7]:
y

135    1
936    0
57     1
620    1
312    1
      ..
244    1
656    0
219    1
526    1
143    0
Name: class, Length: 1000, dtype: int64

In [8]:
x

id  checking_status  duration  credit_history  purpose  credit_amount  \
135  135                3         8               1        6            170   
936  936                2         5               3        6             54   
57    57                3        23               1        6            876   
620  620                0        15               1        0            644   
312  312                2        17               3        3            649   
..   ...              ...       ...             ...      ...            ...   
244  244                3         8               0        8            611   
656  656                0         8               3        4             80   
219  219                3         6               3        4            218   
526  526                3        11               1        2            272   
143  143                1        13               3        3            469   

     savings_status  employment  installment_commitment  personal_status  ...  \
135               4           3                       3                0  ...   
936               2           0                       2                0  ...   
57                2           0                       1                0  ...   
620               2           1                       1                3  ...   
312               2           2                       1                0  ...   
..              ...         ...                     ...              ...  ...   
244               1           0                       3                0  ...   
656               2           3                       3                3  ...   
219               2           0                       1                0  ...   
526               0           0                       3                0  ...   
143               2           0                       1                3  ...   

     residence_since  property_magnitude  age  other_payment_plans  housing  \
135                1                   3   19                    1        1   
936                1                   3    9                    1        1   
57                 1                   0   12                    2        1   
620                2                   1    8                    1        1   
312                3                   0    7                    1        1   
..               ...                 ...  ...                  ...      ...   
244                2                   3   16                    1        1   
656                3                   0   22                    0        1   
219                3                   0   45                    1        1   
526                2                   0   12                    1        1   
143                1                   0    3                    1        1   

     existing_credits  job  num_dependents  own_telephone  foreign_worker  
135                 1    1               0              1               1  
936                 0    3               0              0               1  
57                  1    1               0              0               1  
620                 1    1               0              0               1  
312                 0    1               0              0               1  
..                ...  ...             ...            ...             ...  
244                 0    3               1              0               1  
656                 0    3               1              0               1  
219                 0    1               0              1               1  
526                 0    1               0              0               1  
143                 0    1               0              0               1  

[1000 rows x 21 columns]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [11]:
kCross=10
neigh = KNeighborsClassifier(n_neighbors=6)
scores = cross_val_score(neigh, x, y, cv=kCross, scoring='accuracy')
print(scores)
print('KNN: ',scores.mean())

[0.55 0.68 0.6  0.64 0.59 0.65 0.59 0.65 0.6  0.71]
KNN:  0.6259999999999999


In [12]:
rforest = RandomForestClassifier(n_estimators=500)
rscores = cross_val_score(rforest, x, y, cv=kCross, scoring='accuracy')
print(rscores)
print('RF: ',rscores.mean())

[0.75 0.73 0.8  0.74 0.74 0.74 0.77 0.79 0.71 0.81]
RF:  0.758


In [13]:
dtree = tree.DecisionTreeClassifier(max_depth=30, min_samples_split=20)
dscores = cross_val_score(dtree, x, y, cv=kCross, scoring='accuracy')
print(dscores)
print('DT: ',dscores.mean())

[0.7  0.71 0.72 0.69 0.7  0.76 0.71 0.71 0.6  0.78]
DT:  0.708


In [ ]:
SVM = svm.SVC(kernel='linear', C=1.0, gamma=1)
#SVM = svm.SVC(kernel='poly', degree=2)
#SVM = svm.SVC(kernel='rbf')

scores = cross_val_score(SVM, x, y, cv=kCross, scoring='accuracy')
print(scores)
print('SVM: ',scores.mean())

In [15]:
model=RandomForestClassifier()
model.fit(x_train,y_train)
im=(model.feature_importances_)
im


array([0.09952927, 0.10039734, 0.09207207, 0.05608676, 0.05538355,
       0.11853146, 0.04595497, 0.04268063, 0.04064774, 0.03164306,
       0.01655991, 0.03233576, 0.03282568, 0.1017582 , 0.02602197,
       0.02765676, 0.02148095, 0.02839362, 0.00992644, 0.01757272,
       0.00254116])

In [16]:
imo=pd.Series()
for i in range(d):
    imo= imo.set_value(features[i],im[i])
print(imo)


<ipython-input-16-0c87961504aa>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  imo=pd.Series()


AttributeError: ignored

In [17]:
wf=0.8# wf is used to control the importance of classification accuracy and number of selected features.

dim=len(features)
Max_iter=100
lb=0
ub=1

In [18]:
SearchAgents_no=12
#initialize alpha, beta, and delta_pos
Alpha_pos=np.zeros(dim)
Alpha_score=float(0)
Beta_pos=np.zeros(dim)
Beta_score=float(0)
    
Delta_pos=np.zeros(dim)
Delta_score=float(0)
    
#Initialize the positions of search agents
#transform it into 0 and 1 if greater than 0.5
Positions=np.random.uniform(0,1,(SearchAgents_no,dim)) *(ub-lb)+lb
Convergence_curve=np.zeros(Max_iter)

In [19]:
# this defines the fitness of each crow by calculating their accuracy and no features selected using the below formula
def fit(df2):      # fitness function whose 1 parameter takes the crows and their position as input
    global sel
    sel=[]
    q=0
    imp=0
    a=(df2)==0.0
    if a.all()==True:
        df2[:]=1.0
    for p in range(len(features)):
        if (df2[p]==1.0):
            sel.insert(q,p)
            temp=imo[p]
            imp=imp+temp
        q=q+1
    lf=len(sel)
    divide=lf/lt
    fnt=imp+wf*(1-float(lf/lt))     # fitness formula
    return fnt


In [20]:
time1=time.time()

for l in range(0,Max_iter):

    for i in range(0,SearchAgents_no):
            
            # Calculate objective function for each search agent
        fitness=fit(Positions[i,:])
            # Update Alpha, Beta, and Delta
        if fitness>Alpha_score :
            Alpha_score=fitness; # Update alpha
            Alpha_pos=np.array(Positions[i,:])
        
        if (fitness<Alpha_score and fitness>Beta_score ):
            Beta_score=fitness  # Update beta
            Beta_pos=np.array(Positions[i,:])
            
            
        if (fitness<Alpha_score and fitness<Beta_score and fitness>Delta_score): 
            Delta_score=fitness # Update delta
            Delta_pos=np.array(Positions[i,:])
            
        
        
        
    a=2-l*((2)/Max_iter); # a decreases linearly fron 2 to 0
        
        # Update the Position of search agents including omegas
    for i in range(0,SearchAgents_no):
        for j in range (0,dim):
                           
            r1=random.random() # r1 is a random number in [0,1]
            r2=random.random() # r2 is a random number in [0,1]
                
            A1=2*a*r1-a; # Equation (3.3)
            C1=2*r2; # Equation (3.4)

            D_alpha=abs(C1*Alpha_pos[j]-Positions[i,j]); # Equation (3.5)-part 1
            X1=Alpha_pos[j]-A1*D_alpha; # Equation (3.6)-part 1
            
            r1=random.random()
            r2=random.random()
                
            A2=2*a*r1-a; # Equation (3.3)
            C2=2*r2; # Equation (3.4)
                
            D_beta=abs(C2*Beta_pos[j]-Positions[i,j]); # Equation (3.5)-part 2
            X2=Beta_pos[j]-A2*D_beta; # Equation (3.6)-part 2       
                
            r1=random.random()
            r2=random.random() 
                
            A3=2*a*r1-a; # Equation (3.3)
            C3=2*r2; # Equation (3.4)
                
            D_delta=abs(C3*Delta_pos[j]-Positions[i,j]); # Equation (3.5)-part 3
            X3=Delta_pos[j]-A3*D_delta; # Equation (3.5)-part 3
            
            X=(X1+X2+X3)/3
            sig_X= 1/( 1 + math.exp(( 10*(X-0.5 ) ) ))
            Positions[i,j]= float(sig_X) 

    Positions=(Positions>=random.random()).astype(float)
        
    Convergence_curve[l]=Alpha_score;

    if (l%1==0):
            print(['At iteration '+ str(l)+ ' the best fitness is '+ str(Alpha_score)]);
time2=time.time()
tottime=(time2-time1)
print(tottime)

['At iteration 0 the best fitness is 0.8']


IndexError: ignored

In [21]:
Alpha_pos

array([0.34900085, 0.4845551 , 0.87228054, 0.44091729, 0.70368733,
       0.07318779, 0.96138656, 0.74029158, 0.63592917, 0.18488896,
       0.11688756, 0.53750488, 0.31627501, 0.14742659, 0.42806603,
       0.82833052, 0.48627539, 0.22470065, 0.20723261, 0.02830498,
       0.2049909 , 0.61127086])

In [22]:
q=0

select=[]
for i in range(len(Alpha_pos)):
    if Alpha_pos[i]==1:
        select.insert(q,features[i])
        q=q+1


print('No. of features selected: ',len(select))

print(select)

X=x[select]
Y=y

No. of features selected:  0
[]
